"""crea tablas inventario

Revision ID: c025802323ed
Revises: 3a43f95bb8a4
Create Date: 2026-06-09 18:16:39.140497

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "c025802323ed"
down_revision: str | None = "3a43f95bb8a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suppliers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("nit", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("contacto_nombre", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("telefono", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("direccion", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_suppliers_nombre"), "suppliers", ["nombre"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("sku", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("codigo_barras", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("categoria", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("supplier_id", sa.Integer(), nullable=True),
        sa.Column("precio_costo_centavos", sa.Integer(), nullable=False),
        sa.Column("precio_venta_centavos", sa.Integer(), nullable=False),
        sa.Column(
            "iva",
            sa.Enum("exento", "tarifa_0", "tarifa_5", "tarifa_19", name="ivarate"),
            nullable=False,
        ),
        sa.Column(
            "unidad",
            sa.Enum("unidad", "kg", "g", "litro", "ml", "paquete", name="productunit"),
            nullable=False,
        ),
        sa.Column("stock_milesimas", sa.Integer(), nullable=False),
        sa.Column("stock_minimo_milesimas", sa.Integer(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("precio_costo_centavos >= 0", name="ck_products_precio_costo_no_neg"),
        sa.CheckConstraint("precio_venta_centavos >= 0", name="ck_products_precio_venta_no_neg"),
        sa.CheckConstraint("stock_milesimas >= 0", name="ck_products_stock_no_neg"),
        sa.CheckConstraint("stock_minimo_milesimas >= 0", name="ck_products_stock_min_no_neg"),
        sa.ForeignKeyConstraint(["supplier_id"], ["suppliers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_categoria"), "products", ["categoria"], unique=False)
    op.create_index(op.f("ix_products_codigo_barras"), "products", ["codigo_barras"], unique=True)
    op.create_index(op.f("ix_products_nombre"), "products", ["nombre"], unique=False)
    op.create_index(op.f("ix_products_sku"), "products", ["sku"], unique=True)
    op.create_table(
        "inventory_movements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum("entrada", "salida", "ajuste", "merma", name="movementtype"),
            nullable=False,
        ),
        sa.Column("cantidad_milesimas", sa.Integer(), nullable=False),
        sa.Column("costo_unitario_centavos", sa.Integer(), nullable=True),
        sa.Column("stock_resultante_milesimas", sa.Integer(), nullable=False),
        sa.Column("motivo", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("cantidad_milesimas > 0", name="ck_movements_cantidad_pos"),
        sa.CheckConstraint(
            "costo_unitario_centavos IS NULL OR costo_unitario_centavos >= 0",
            name="ck_movements_costo_no_neg",
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_movements_created_at"),
        "inventory_movements",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_product_id"),
        "inventory_movements",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        "ix_movements_product_created",
        "inventory_movements",
        ["product_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_movements_product_created", table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_product_id"), table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_created_at"), table_name="inventory_movements")
    op.drop_table("inventory_movements")
    op.drop_index(op.f("ix_products_sku"), table_name="products")
    op.drop_index(op.f("ix_products_nombre"), table_name="products")
    op.drop_index(op.f("ix_products_codigo_barras"), table_name="products")
    op.drop_index(op.f("ix_products_categoria"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_suppliers_nombre"), table_name="suppliers")
    op.drop_table("suppliers")
    # ### end Alembic commands ###
    # Eliminar los tipos enum explícitamente: el autogenerate no lo hace y, si no,
    # quedan huérfanos tras un rollback (caso conocido con 'userrole' en Fase 0).
    for enum_name in ("movementtype", "ivarate", "productunit"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
